name: Extraction Vivatech DGITM

on:
  workflow_dispatch:

jobs:
  scraping:
    runs-on: ubuntu-latest
    env:
      # Force l'utilisation des versions à jour de GitHub pour faire taire l'alerte
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Passage à la version 24

      - name: Installation de Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install --with-deps chromium

      - name: Lancement de l'extraction
        run: node vivatech.js

      - name: Mise à disposition des fichiers
        uses: actions/upload-artifact@v4
        if: always() # Obligatoire pour récupérer la photo même si l'extraction échoue
        with:
          name: Vivatech_Resultats_DGITM
          path: |
            Vivatech_Exhibitors_DGITM.csv
            debug-vivatech.png*
          retention-days: 5
